import './globals.css';
import { Inter } from 'next/font/google';
import { cn } from '../lib/utils';
import { ThemeProvider } from '../components/ui/theme-provider';
import { Toaster } from 'react-hot-toast';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: 'Matrix Simulator',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={cn('min-h-screen bg-background font-sans antialiased', inter.className)}>
        <ThemeProvider attribute="class" defaultTheme="light" enableSystem>
          <Toaster 
            position="top-center"
            toastOptions={{
              duration: 3000,
            }}
          />
          {children}
        </ThemeProvider>
      </body>
    </html>
  );
}
